<?php


return [
    [
        "id" => 1,
        "name" => "Районы республиканского подчинения",
        "name_tj" => "Ноҳияҳои тобеи ҷумҳурӣ",
        "name_en" => "Districts of republican subordination",
        "region_type_id" => $regionType,
        "parent_id" => 0,
    ],
    [
        "id" => 2,
        "name" => "Согдийская область",
        "name_tj" => "Вилояти Суғд",
        "name_en" => "Sughd region",
        "region_type_id" => $regionType,
        "parent_id" => 0,
    ],
    [
        "id" => 3,
        "name" => "Хатлонская область",
        "name_tj" => "Вилояти Хатлон",
        "name_en" => "Khatlon region",
        "region_type_id" => $regionType,
        "parent_id" => 0,
    ],
    [
        "id" => 4,
        "name" => "ГБАО",
        "name_tj" => "ВМКБ",
        "name_en" => "GBAO",
        "region_type_id" => $regionType,
        "parent_id" => 0,
    ],
    [
        "id" => 9,
        "name" => "Айни",
        "name_tj" => "Айнӣ",
        "name_en" => "Ayni",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 14,
        "name" => "Ашт",
        "name_tj" => "Ашт",
        "name_en" => "Asht",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 16,
        "name" => "Файзобад",
        "name_tj" => "Файзобод",
        "name_en" => "Fayzabad",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 17,
        "name" => "Гисар",
        "name_tj" => "Ҳисор",
        "name_en" => "Gisar",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 18,
        "name" => "Лахш",
        "name_tj" => "Лахш",
        "name_en" => "Jirgatol",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 19,
        "name" => "Нуробод",
        "name_tj" => "Нуробод",
        "name_en" => "Nurobod",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 20,
        "name" => "Рашт",
        "name_tj" => "Рашт",
        "name_en" => "Rasht",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 21,
        "name" => "Рогун",
        "name_tj" => "Роғун",
        "name_en" => "Rogun",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 22,
        "name" => "Рудаки",
        "name_tj" => "Рудаки",
        "name_en" => "Rudaki",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 23,
        "name" => "Шахринав",
        "name_tj" => "Шаҳринав",
        "name_en" => "Shahrinav",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 24,
        "name" => "Тавилдара",
        "name_tj" => "Тавилдара",
        "name_en" => "Tavildara",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 25,
        "name" => "Таджикобад",
        "name_tj" => "Тоҷикобод",
        "name_en" => "Tojikobad",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 26,
        "name" => "Турсунзаде",
        "name_tj" => "Турсунзаде",
        "name_en" => "Tursunzade",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 27,
        "name" => "Вахдат",
        "name_tj" => "Ваҳдат",
        "name_en" => "Vahdat",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 28,
        "name" => "Варзоб",
        "name_tj" => "Варзоб",
        "name_en" => "Varzob",
        "region_type_id" => $districtType,
        "parent_id" => 1,
    ],
    [
        "id" => 29,
        "name" => "Б. Гафуров",
        "name_tj" => "Б. Ғафуров ",
        "name_en" => "B. Gafurov",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 30,
        "name" => "Деваштич",
        "name_tj" => "Деваштич",
        "name_en" => "Devashtich",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 31,
        "name" => "Исфара",
        "name_tj" => "Исфара",
        "name_en" => "Isfara ",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 32,
        "name" => "Истаравшан",
        "name_tj" => "Истаравшан",
        "name_en" => "Istarafshan",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 33,
        "name" => "Дж. Расулов",
        "name_tj" => "Ҷ. Расулов",
        "name_en" => "J. Rasulov",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 34,
        "name" => "Канибадам",
        "name_tj" => "Конибодом",
        "name_en" => "Kanibadam",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 35,
        "name" => "Мастчохи Кухи",
        "name_tj" => "Мастчоҳи Кӯҳӣ",
        "name_en" => "Kuhistoni Mastchoh",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 36,
        "name" => "Мастчох",
        "name_tj" => "Мастчоҳ",
        "name_en" => "Mastchoh",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 37,
        "name" => "Пянджикент",
        "name_tj" => "Панҷакент",
        "name_en" => "Panjakent",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 38,
        "name" => "Шахристан",
        "name_tj" => "Шаҳристон",
        "name_en" => "Shahristan",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 39,
        "name" => "Спитамен",
        "name_tj" => "Спитамен",
        "name_en" => "Spitamen",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 40,
        "name" => "Зафарабад",
        "name_tj" => "Зафаробод",
        "name_en" => "Zafarabad",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
    [
        "id" => 41,
        "name" => "Балджувон",
        "name_tj" => "Балҷувон",
        "name_en" => "Baljuvan ",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 42,
        "name" => "Кушониён",
        "name_tj" => "Кӯшониён ",
        "name_en" => "Bokhtar",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 43,
        "name" => "Дангара",
        "name_tj" => "Данғара",
        "name_en" => "Danghara",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 44,
        "name" => "Фархор",
        "name_tj" => "Фархор",
        "name_en" => "Farkhor",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 45,
        "name" => "Хамадони",
        "name_tj" => "Ҳамадонӣ",
        "name_en" => "Khamadoni",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 46,
        "name" => "Дусти",
        "name_tj" => "Дӯстӣ",
        "name_en" => "Dusti",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 47,
        "name" => "А. Джами",
        "name_tj" => "А. Ҷомӣ",
        "name_en" => "A. Jomi",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 48,
        "name" => "Ховалинг",
        "name_tj" => "Ховалинг",
        "name_en" => "Khovaling",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 49,
        "name" => "Хуросон",
        "name_tj" => "Хуросон",
        "name_en" => "Khuroson",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 50,
        "name" => "Куляб",
        "name_tj" => "Кӯлоб",
        "name_en" => "Kulob",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 51,
        "name" => "Муминобод",
        "name_tj" => "Муъминобод ",
        "name_en" => "Muminabad",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 52,
        "name" => "Норак",
        "name_tj" => "Норак",
        "name_en" => "Norak",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 53,
        "name" => "Н. Хусрав",
        "name_tj" => "Н. Хусрав",
        "name_en" => "N. Khusrav",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 54,
        "name" => "Пяндж",
        "name_tj" => "Панҷ ",
        "name_en" => "Panj",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 55,
        "name" => "Кабадиян",
        "name_tj" => "Қубодиён",
        "name_en" => "Qubodiyon",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 56,
        "name" => "Джайхун",
        "name_tj" => "Ҷайҳун",
        "name_en" => "Jayhun",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 57,
        "name" => "Дж. Балхи",
        "name_tj" => "Ҷ. Балхӣ",
        "name_en" => "J. Balhi",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 58,
        "name" => "Левакант",
        "name_tj" => "Левакант",
        "name_en" => "Sarband",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 59,
        "name" => "Шахритуз",
        "name_tj" => "Шаҳритуз",
        "name_en" => "Shahrituz",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 60,
        "name" => "Ш. Шохин",
        "name_tj" => "Ш. Шоҳин",
        "name_en" => "Sh. Shohin",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 61,
        "name" => "Темурмалик",
        "name_tj" => "Темурмалик",
        "name_en" => "Temurmalik",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 62,
        "name" => "Вахш",
        "name_tj" => "Вахш",
        "name_en" => "Vahsh",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 63,
        "name" => "Восе",
        "name_tj" => "Восеъ",
        "name_en" => "Vose",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 64,
        "name" => "Яван",
        "name_tj" => "Ёвон",
        "name_en" => "Yovon",
        "region_type_id" => $districtType,
        "parent_id" => 3,
    ],
    [
        "id" => 65,
        "name" => "Дарваз",
        "name_tj" => "Дарвоз",
        "name_en" => "Darvoz",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 66,
        "name" => "Ишкашим",
        "name_tj" => "Ишкошим",
        "name_en" => "Ishkoshim",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 67,
        "name" => "Мургаб",
        "name_tj" => "Мурғоб",
        "name_en" => "Murghob",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 68,
        "name" => "Рошткала",
        "name_tj" => "Роштқалъа",
        "name_en" => "Roshtqal’a",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 69,
        "name" => "Рушан",
        "name_tj" => "Рушон ",
        "name_en" => "Rushan",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 70,
        "name" => "Шугнан",
        "name_tj" => "Шуғнон",
        "name_en" => "Shughnon",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 71,
        "name" => "Вандж",
        "name_tj" => "Ванҷ",
        "name_en" => "Vanj",
        "region_type_id" => $districtType,
        "parent_id" => 4,
    ],
    [
        "id" => 76,
        "name" => "Бустон",
        "name_tj" => "Бӯстон",
        "name_en" => "Buston",
        "region_type_id" => $districtType,
        "parent_id" => 2,
    ],
];
